[package]
name = "verify_no_std"
version = "0.0.0"
publish = false
edition = "2021"

[dependencies]
lazy_static = { version = "1.5.0", features = ["spin_no_std"] }
zcash_script = { path = "..", default-features = false }
